### ISSUE TITLE
Such events dont exists

### ISSUE THREAD

**Issue by Soulbadguy54** [bombsimon/hltv-python#10]
I cant get events like MatchStarted or mapChange. Can someone get this type of updates? Im using pure socket-io, but issue cant be bound with that fact...

**Comment by bombsimon** [comment]
It is absolutely possible these events no longer exist. I think the `MapChange` event was just ported from https://github.com/Nols1000/hltv-scorebot however since the `MatchStarted` event has documentation I assume I must've seen it when writing the docs. That doesn't mean it's still there though.

I would suggest setting up a socket and register all events. If some of them no longer exist feel free to make a PR to remove them!

**Comment by bombsimon** [comment]
I did some quick check with an old match. As you can see in the code we skip the playback but this is basically the events that happened so far: https://github.com/bombsimon/hltv-python/blob/6b882fea88245c239fc034892f75898d65adcb0c/scorebot/scorebot.py#L188-L191

I checked on an old match by grabbing all the events seen:

```python
seen_events = list({ event: True for events in logs for event in events }.keys())
```

There is indeed a `MatchStarted` event and if I look at that it looks like the docs says:

```json
[{"map": "de_mirage"}]
```

I think the whole `MapChange` only happens in old style BOx events where the players stayed on the same server. I don't know if this is how CS:GO actually handles multiple games/BO style games anymore and if not it makes sense that event will never be omitted. 

Do you have an example of a game where you expected a `MapChange` event but didn't get one?

**Comment by Soulbadguy54** [comment]
I use this function for handle this event:
```
async def _map_change_handler(data):
    with open("change_sample.json", "a+") as outfile:
        outfile.write('\n\n\n')
        outfile.write(ujson.dumps(data))
```
And this way for register callbacks:
`self.sio.on(key, func)` , where key is event_name and func the function above. I tried to use "mapChange", "mapchange", "MapChange" for 3 different functions. But there are no json files was saved, which means that i dont get this type of callbacks. 

PS. "score", "scoreboard", "connect", "disconnect" events work as usual
PSS. sorry for bad eng

**Comment by bombsimon** [comment]
Why did you expect that event? Are you listening to a match with multiple rounds where they do change the map?

**Comment by bombsimon** [comment]
I found this game that was a BO3: https://www.hltv.org/matches/2359995/mouz-nxt-vs-og-academy-mistgames-heroes-of-tomorrow-fall-2022

If I look at the log for that one it contains two games:

```json
[
  {
    "MatchStarted": {
      "map": "de_inferno"
    }
  },
...
  {
    "MatchStarted": {
      "map": "de_overpass"                                                                                                                                                                                                                                                                                                                                                   }
  }
]
```

There seem to be no `MapChange` event between these so the event apparently no longer exists. I'll remove it.

**Comment by Soulbadguy54** [comment]
> Why did you expect that event? Are you listening to a match with multiple games where they do change the map?

Yea, i was listening for every game and round on hltv :)

What i want is to understand when the match really starts. I had some troubles with the warm-up, since sometimes my code logic counts warm-up rounds like the main game. 
I want to catch matchStart event, set the score to 0:0.

But I had the same problem with matchStart event. No handler reaches this type of event. Where can i find it? Only in logs? When i use `sio.on("log", handler)`, or like `sio.on("matchStart", handler)` as well?

Thx for your time

**Comment by bombsimon** [comment]
If you are connected to the game before it starts you should see a `MatchStarted` event but yes, it's also in the logs. There will be several of this event due to warmups like you said. Maybe easiest would be to keep track of the scoreboard event and assume a game is started every time all players hav 0 0 0 in their stats.

I actually don't use this code myself so I don't really know what the best way would be. If you find improvements that can be done to ease your use case feel free to file a PR!
